[tool.poetry]
name = "learntosolveit"
version = "0.1.0"
description = ""
authors = ["Senthil Kumaran <senthil@python.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
